import type { RouteRegistry } from './route-types'
import { buildDeductionEntryHrefByBasisId } from '../data/fcs/quality-chain-adapter'
import { renderRouteRedirect } from './route-utils'
import {
  renderTaskBreakdownPage,
  renderCapabilityPage,
  renderFactoryCapacityProfilePage,
  renderFactoryPerformancePage,
  renderFactoryProfilePage,
  renderFactoryStatusPage,
  renderOverviewPage,
  renderTodosPage,
  renderCapacityBottleneckPage,
  renderCapacityConstraintsPage,
  renderCapacityOverviewPage,
  renderCapacityPoliciesPage,
  renderCapacityRiskPage,
  renderProductionChangesPage,
  renderProductionCraftDictPage,
  renderProductionDemandInboxPage,
  renderProductionDeliveryWarehousePage,
  renderProductionOrderDetailPage,
  renderProductionOrdersPage,
  renderProductionPlanPage,
  renderProductionStatusPage,
  renderProcessDyeOrdersPage,
  renderProcessDyeRequirementsPage,
  renderProcessPrintOrdersPage,
  renderProcessPrintRequirementsPage,
  renderMaterialIssuePage,
  renderQcRecordDetailPage,
  renderQcRecordsPage,
  renderDeductionAnalysisPage,
  renderBatchesPage,
  renderSettlementListPage,
  renderSettlementDetailPage,
  renderSettlementInitPage,
  renderFcsProductionTechPackSnapshotPage,
  renderMaterialStatementsPage,
  renderHistoryPage,
  renderPaymentSyncPage,
  renderStatementsPage,
  renderAdjustmentsPage,
  renderDispatchBoardPage,
  renderDispatchTendersPage,
  renderProgressBoardPage,
  renderProgressCuttingDetailPage,
  renderProgressCuttingExceptionCenterPage,
  renderProgressCuttingOverviewPage,
  renderProgressExceptionsPage,
  renderProgressHandoverOrderPage,
  renderProgressHandoverPage,
  renderProgressMaterialPage,
  renderProgressMilestoneConfigPage,
  renderProgressUrgePage,
  renderCraftWorkbenchOverviewPage,
  renderCraftCuttingCuttablePoolPage,
  renderCraftCuttingCutPieceWarehousePage,
  renderCraftCuttingFeiTicketContinuePrintPage,
  renderCraftCuttingFeiTicketDetailPage,
  renderCraftCuttingFeiTicketPrintedPage,
  renderCraftCuttingFeiTicketReprintPage,
  renderCraftCuttingFeiTicketRecordsPage,
  renderCraftCuttingFeiTicketVoidPage,
  renderCraftCuttingFeiTicketsPage,
  renderCraftCuttingMaterialPrepPage,
  renderCraftCuttingMergeBatchesPage,
  renderCraftCuttingOriginalOrdersPage,
  renderCraftCuttingProductionProgressPage,
  renderPlaceholderPage,
  renderCraftCuttingMarkerCreatePage,
  renderCraftCuttingMarkerListPage,
  renderCraftCuttingMarkerPlanDetailPage,
  renderCraftCuttingMarkerPlanEditPage,
  renderCraftCuttingMarkerSpreadingPage,
  renderCraftCuttingReplenishmentPage,
  renderCraftCuttingSampleWarehousePage,
  renderCraftCuttingSpecialProcessesPage,
  renderCraftCuttingSpreadingCreatePage,
  renderCraftCuttingSpreadingDetailPage,
  renderCraftCuttingSpreadingEditPage,
  renderCraftCuttingSpreadingListPage,
  renderCraftCuttingSummaryPage,
  renderCraftCuttingTransferBagDetailPage,
  renderCraftCuttingTransferBagsPage,
  renderCraftCuttingFabricWarehousePage,
  renderCraftPrintingDashboardsPage,
  renderCraftPrintingPendingReviewPage,
  renderCraftPrintingProgressPage,
  renderCraftPrintingStatisticsPage,
  renderCraftPrintingWorkOrdersPage,
  renderCraftDyeingDyeOrdersPage,
  renderCraftDyeingReportsPage,
  renderCraftDyeingWorkOrdersPage,
  renderTraceMappingPage,
  renderTraceParentCodesPage,
  renderTraceUniqueCodesPage,
  renderTraceUnitPricePage,
  renderCuttingSettlementInputPage,
} from './route-renderers-fcs'

export const routes: RouteRegistry = {
  exactRoutes: {
    '/fcs/factories/profile': () => renderFactoryProfilePage(),
    '/fcs/factories/capacity-profile': () => renderFactoryCapacityProfilePage(),
    '/fcs/factories/capability': () => renderCapabilityPage(),
    '/fcs/factories/status': () => renderFactoryStatusPage(),
    '/fcs/factories/performance': () => renderFactoryPerformancePage(),
    '/fcs/factories/settlement': () => renderSettlementListPage(),
    '/fcs/factories/settlement/new': () => renderSettlementListPage(),
    '/fcs/workbench/overview': () => renderOverviewPage(),
    '/fcs/workbench/todos': () => renderTodosPage(),
    '/fcs/capacity/overview': () => renderCapacityOverviewPage(),
    '/fcs/capacity/risk': () => renderCapacityRiskPage(),
    '/fcs/capacity/bottleneck': () => renderCapacityBottleneckPage(),
    '/fcs/capacity/constraints': () => renderCapacityConstraintsPage(),
    '/fcs/capacity/policies': () => renderCapacityPoliciesPage(),
    '/fcs/production/demand-inbox': () => renderProductionDemandInboxPage(),
    '/fcs/production/orders': () => renderProductionOrdersPage(),
    '/fcs/production/plan': () => renderProductionPlanPage(),
    '/fcs/production/delivery-warehouse': () => renderProductionDeliveryWarehousePage(),
    '/fcs/production/changes': () => renderProductionChangesPage(),
    '/fcs/production/status': () => renderProductionStatusPage(),
    '/fcs/production/craft-dict': () => renderProductionCraftDictPage(),
    '/fcs/process/task-breakdown': () => renderTaskBreakdownPage(),
    '/fcs/process/dye-requirements': () => renderProcessDyeRequirementsPage(),
    '/fcs/process/print-requirements': () => renderProcessPrintRequirementsPage(),
    '/fcs/process/dye-orders': () => renderProcessDyeOrdersPage(),
    '/fcs/process/print-orders': () => renderProcessPrintOrdersPage(),
    '/fcs/process/material-issue': () => renderMaterialIssuePage(),
    '/fcs/quality/qc-records': () => renderQcRecordsPage(),
    '/fcs/quality/deduction-analysis': () => renderDeductionAnalysisPage(),
    '/fcs/quality/deduction-calc': () =>
      renderRouteRedirect('/fcs/quality/deduction-analysis', '正在跳转到扣款分析'),
    '/fcs/quality/arbitration': () =>
      renderRouteRedirect('/fcs/quality/qc-records?view=WAIT_PLATFORM_REVIEW', '正在跳转到质检记录'),
    '/fcs/quality/penalty-output': () => renderDeductionAnalysisPage(),
    '/fcs/settlement/statements': () => renderStatementsPage(),
    '/fcs/settlement/adjustments': () => renderAdjustmentsPage(),
    '/fcs/settlement/batches': () => renderBatchesPage(),
    '/fcs/settlement/material-statements': () => renderMaterialStatementsPage(),
    '/fcs/settlement/payment-sync': () => renderPaymentSyncPage(),
    '/fcs/settlement/history': () => renderHistoryPage(),
    '/fcs/settlement/cutting-input': () =>
      renderRouteRedirect('/fcs/craft/cutting/settlement-scoring', '正在跳转到裁片结算评分'),
    '/fcs/dispatch/board': () => renderDispatchBoardPage(),
    '/fcs/dispatch/tenders': () => renderDispatchTendersPage(),
    '/fcs/dispatch/exceptions': () => renderProgressExceptionsPage(),
    '/fcs/progress/board': () => renderProgressBoardPage(),
    '/fcs/progress/exceptions': () => renderProgressExceptionsPage(),
    '/fcs/progress/handover': () => renderProgressHandoverPage(),
    '/fcs/progress/urge': () => renderProgressUrgePage(),
    '/fcs/progress/milestone-config': () => renderProgressMilestoneConfigPage(),
    '/fcs/progress/material': () => renderProgressMaterialPage(),
    '/fcs/progress/cutting-overview': () => renderProgressCuttingOverviewPage(),
    '/fcs/progress/cutting-exception-center': () => renderProgressCuttingExceptionCenterPage(),
    '/fcs/craft/workbench/overview': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/workbench/todos': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/workbench/risks': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/cutting': () =>
      renderRouteRedirect('/fcs/craft/cutting/production-progress', '正在跳转到生产单进度'),
    '/fcs/craft/cutting/production-progress': () => renderCraftCuttingProductionProgressPage(),
    '/fcs/craft/cutting/cuttable-pool': () => renderCraftCuttingCuttablePoolPage(),
    '/fcs/craft/cutting/merge-batches': () => renderCraftCuttingMergeBatchesPage(),
    '/fcs/craft/cutting/original-orders': () => renderCraftCuttingOriginalOrdersPage(),
    '/fcs/craft/cutting/marker-list': () => renderCraftCuttingMarkerListPage(),
    '/fcs/craft/cutting/marker-create': () => renderCraftCuttingMarkerCreatePage(),
    '/fcs/craft/cutting/spreading-list': () => renderCraftCuttingSpreadingListPage(),
    '/fcs/craft/cutting/spreading-create': () => renderCraftCuttingSpreadingCreatePage(),
    '/fcs/craft/cutting/marker-spreading': () => renderCraftCuttingMarkerSpreadingPage(),
    '/fcs/craft/cutting/settlement-scoring': () => renderCuttingSettlementInputPage(),
    '/fcs/craft/cutting/marker-detail': () =>
      renderRouteRedirect('/fcs/craft/cutting/marker-list', '正在跳转到唛架列表'),
    '/fcs/craft/cutting/marker-edit': () =>
      renderRouteRedirect('/fcs/craft/cutting/marker-list', '正在跳转到唛架列表'),
    '/fcs/craft/cutting/spreading-detail': () => renderCraftCuttingSpreadingDetailPage(),
    '/fcs/craft/cutting/spreading-edit': () => renderCraftCuttingSpreadingEditPage(),
    '/fcs/craft/cutting/fei-tickets': () => renderCraftCuttingFeiTicketsPage(),
    '/fcs/craft/cutting/fei-ticket-detail': () => renderCraftCuttingFeiTicketDetailPage(),
    '/fcs/craft/cutting/fei-ticket-printed': () => renderCraftCuttingFeiTicketPrintedPage(),
    '/fcs/craft/cutting/fei-ticket-records': () => renderCraftCuttingFeiTicketRecordsPage(),
    '/fcs/craft/cutting/fei-ticket-print': () => renderCraftCuttingFeiTicketPrintedPage(),
    '/fcs/craft/cutting/fei-ticket-continue-print': () => renderCraftCuttingFeiTicketContinuePrintPage(),
    '/fcs/craft/cutting/fei-ticket-reprint': () => renderCraftCuttingFeiTicketReprintPage(),
    '/fcs/craft/cutting/fei-ticket-void': () => renderCraftCuttingFeiTicketVoidPage(),
    '/fcs/craft/cutting/fabric-warehouse': () => renderCraftCuttingFabricWarehousePage(),
    '/fcs/craft/cutting/cut-piece-warehouse': () => renderCraftCuttingCutPieceWarehousePage(),
    '/fcs/craft/cutting/sample-warehouse': () => renderCraftCuttingSampleWarehousePage(),
    '/fcs/craft/cutting/transfer-bags': () => renderCraftCuttingTransferBagsPage(),
    '/fcs/craft/cutting/transfer-bag-detail': () => renderCraftCuttingTransferBagDetailPage(),
    '/fcs/craft/cutting/special-processes': () => renderCraftCuttingSpecialProcessesPage(),
    '/fcs/craft/cutting/summary': () => renderCraftCuttingSummaryPage(),
    '/fcs/craft/cutting/order-progress': () =>
      renderRouteRedirect('/fcs/craft/cutting/production-progress', '正在跳转到生产单进度'),
    '/fcs/craft/cutting/tasks': () =>
      renderRouteRedirect('/fcs/craft/cutting/production-progress', '正在跳转到生产单进度'),
    '/fcs/craft/cutting/material-prep': () => renderCraftCuttingMaterialPrepPage(),
    '/fcs/craft/cutting/orders': () =>
      renderRouteRedirect('/fcs/craft/cutting/original-orders', '正在跳转到原始裁片单'),
    '/fcs/craft/cutting/cut-piece-orders': () =>
      renderRouteRedirect('/fcs/craft/cutting/original-orders', '正在跳转到原始裁片单'),
    '/fcs/craft/cutting/fei-ticket': () =>
      renderRouteRedirect('/fcs/craft/cutting/fei-tickets', '正在跳转到打印菲票'),
    '/fcs/craft/cutting/fei-list': () =>
      renderRouteRedirect('/fcs/craft/cutting/fei-tickets', '正在跳转到打印菲票'),
    '/fcs/craft/cutting/warehouse': () =>
      renderRouteRedirect('/fcs/craft/cutting/fabric-warehouse', '正在跳转到裁床仓'),
    '/fcs/craft/cutting/warehouse-management': () =>
      renderRouteRedirect('/fcs/craft/cutting/fabric-warehouse', '正在跳转到裁床仓'),
    '/fcs/craft/cutting/replenishment': () => renderCraftCuttingReplenishmentPage(),
    '/fcs/craft/cutting/stats': () =>
      renderRouteRedirect('/fcs/craft/cutting/summary', '正在跳转到裁剪总表'),
    '/fcs/craft/cutting/bed-stats': () =>
      renderRouteRedirect('/fcs/craft/cutting/summary', '正在跳转到裁剪总表'),
    '/fcs/craft/cutting/cutting-summary': () =>
      renderRouteRedirect('/fcs/craft/cutting/summary', '正在跳转到裁剪总表'),
    '/fcs/craft/printing': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/work-orders': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/tasks': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/orders': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/pending-review': () => renderCraftPrintingPendingReviewPage(),
    '/fcs/craft/printing/batches': () => renderCraftPrintingPendingReviewPage(),
    '/fcs/craft/printing/progress': () => renderCraftPrintingProgressPage(),
    '/fcs/craft/printing/stats': () => renderCraftPrintingStatisticsPage(),
    '/fcs/craft/printing/statistics': () => renderCraftPrintingStatisticsPage(),
    '/fcs/craft/printing/dashboards': () => renderCraftPrintingDashboardsPage(),
    '/fcs/craft/dyeing': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/work-orders': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/tasks': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/orders': () => renderCraftDyeingDyeOrdersPage(),
    '/fcs/craft/dyeing/dye-orders': () => renderCraftDyeingDyeOrdersPage(),
    '/fcs/craft/dyeing/batches': () => renderCraftDyeingDyeOrdersPage(),
    '/fcs/craft/dyeing/stats': () => renderCraftDyeingReportsPage(),
    '/fcs/craft/dyeing/reports': () => renderCraftDyeingReportsPage(),
    '/fcs/production/create': () =>
      renderPlaceholderPage(
        '生成生产单',
        '根据生产需求创建生产单，包括拆单规则配置、批次划分、工艺路线选择等。',
        '生产单管理',
      ),
    '/fcs/trace/mapping': () => renderTraceMappingPage(),
    '/fcs/trace/parent-codes': () => renderTraceParentCodesPage(),
    '/fcs/trace/unique-codes': () => renderTraceUniqueCodesPage(),
    '/fcs/trace/unit-price': () => renderTraceUnitPricePage(),
  },
  dynamicRoutes: [
    {
      pattern: /^\/fcs\/craft\/cutting\/marker-edit\/([^/]+)$/,
      render: (match) => renderCraftCuttingMarkerPlanEditPage(match[1]),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/marker-detail\/([^/]+)$/,
      render: (match) => renderCraftCuttingMarkerPlanDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/orders\/([^/]+)\/tech-pack$/,
      render: (match) => renderFcsProductionTechPackSnapshotPage(match[1]),
    },
    {
      pattern: /^\/fcs\/factories\/settlement\/new\/([^/]+)$/,
      render: (match) => renderSettlementInitPage(match[1]),
    },
    {
      pattern: /^\/fcs\/factories\/settlement\/([^/]+)$/,
      render: (match) => renderSettlementDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/quality\/qc-records\/([^/]+)$/,
      render: (match) => renderQcRecordDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/quality\/deduction-calc\/([^/]+)$/,
      render: (match) =>
        renderRouteRedirect(
          buildDeductionEntryHrefByBasisId(decodeURIComponent(match[1])),
          '正在跳转到关联质检记录',
        ),
    },
    {
      pattern: /^\/fcs\/production\/orders\/([^/]+)$/,
      render: (match) => renderProductionOrderDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/progress\/cutting-overview\/([^/]+)$/,
      render: (match) => renderProgressCuttingDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/progress\/handover\/order\/([^/]+)$/,
      render: (match) => renderProgressHandoverOrderPage(match[1]),
    },
  ],
}
