export const PDA_CUTTING_INTEGRATION_MAP = [
  {
    from: 'task-list',
    to: 'task-receive-detail',
    carry: ['taskId', 'returnTo', 'sourcePageKey', 'focusTaskId', 'highlightTask', 'autoFocus'],
    returnsTo: 'task-list',
    focusTarget: 'task-card',
    refreshTargets: ['task-list', 'task-receive-detail'],
  },
  {
    from: 'task-receive-detail',
    to: 'cutting-task-detail',
    carry: ['taskId', 'returnTo', 'sourcePageKey', 'focusTaskId'],
    returnsTo: 'task-receive-detail',
    focusTarget: 'task-summary',
    refreshTargets: ['task-receive-detail', 'cutting-task-detail'],
  },
  {
    from: 'cutting-task-detail',
    to: 'pickup',
    carry: ['taskId', 'executionOrderId', 'executionOrderNo', 'originalCutOrderId', 'originalCutOrderNo', 'mergeBatchId', 'mergeBatchNo', 'materialSku', 'returnTo', 'sourcePageKey', 'focusTaskId', 'focusExecutionOrderId', 'focusExecutionOrderNo', 'focusActionKey'],
    returnsTo: 'cutting-task-detail',
    focusTarget: 'execution-order-card',
    refreshTargets: ['cutting-task-detail', 'task-receive-detail', 'task-list'],
  },
  {
    from: 'cutting-task-detail',
    to: 'spreading',
    carry: ['taskId', 'executionOrderId', 'executionOrderNo', 'originalCutOrderId', 'originalCutOrderNo', 'mergeBatchId', 'mergeBatchNo', 'materialSku', 'returnTo', 'sourcePageKey', 'focusTaskId', 'focusExecutionOrderId', 'focusExecutionOrderNo', 'focusActionKey'],
    returnsTo: 'cutting-task-detail',
    focusTarget: 'execution-order-card',
    refreshTargets: ['cutting-task-detail', 'task-receive-detail', 'task-list'],
  },
  {
    from: 'cutting-task-detail',
    to: 'inbound',
    carry: ['taskId', 'executionOrderId', 'executionOrderNo', 'originalCutOrderId', 'originalCutOrderNo', 'mergeBatchId', 'mergeBatchNo', 'materialSku', 'returnTo', 'sourcePageKey', 'focusTaskId', 'focusExecutionOrderId', 'focusExecutionOrderNo', 'focusActionKey'],
    returnsTo: 'cutting-task-detail',
    focusTarget: 'execution-order-card',
    refreshTargets: ['cutting-task-detail', 'task-receive-detail', 'task-list'],
  },
  {
    from: 'cutting-task-detail',
    to: 'handover',
    carry: ['taskId', 'executionOrderId', 'executionOrderNo', 'originalCutOrderId', 'originalCutOrderNo', 'mergeBatchId', 'mergeBatchNo', 'materialSku', 'returnTo', 'sourcePageKey', 'focusTaskId', 'focusExecutionOrderId', 'focusExecutionOrderNo', 'focusActionKey'],
    returnsTo: 'cutting-task-detail',
    focusTarget: 'execution-order-card',
    refreshTargets: ['cutting-task-detail', 'task-receive-detail', 'task-list'],
  },
  {
    from: 'cutting-task-detail',
    to: 'replenishment-feedback',
    carry: ['taskId', 'executionOrderId', 'executionOrderNo', 'originalCutOrderId', 'originalCutOrderNo', 'mergeBatchId', 'mergeBatchNo', 'materialSku', 'returnTo', 'sourcePageKey', 'focusTaskId', 'focusExecutionOrderId', 'focusExecutionOrderNo', 'focusActionKey'],
    returnsTo: 'cutting-task-detail',
    focusTarget: 'execution-order-card',
    refreshTargets: ['cutting-task-detail', 'task-receive-detail', 'task-list'],
  },
] as const
